# Write build configuration for reference
# NOTE: .env is now the SOURCE of configuration (via LoadEnv.cmake)
# This file writes to .env.generated for debugging/reference purposes only

set (env_file "${PROJECT_SOURCE_DIR}/.env.generated")
message (STATUS "Writing generated config to: ${env_file}")

# the first call truncates, the rest append
file(WRITE  "${env_file}" "# Auto-generated by CMake - DO NOT EDIT\n")
file(APPEND "${env_file}" "# Source of truth is .env file\n\n")
file(APPEND "${env_file}" "PROJECT_NAME=${PROJECT_NAME}\n")
file(APPEND "${env_file}" "PRODUCT_NAME=\"${PRODUCT_NAME}\"\n")
file(APPEND "${env_file}" "VERSION=${CURRENT_VERSION}\n")
file(APPEND "${env_file}" "MAJOR_VERSION=${MAJOR_VERSION}\n")
file(APPEND "${env_file}" "BUNDLE_ID=${BUNDLE_ID}\n")
file(APPEND "${env_file}" "COMPANY_NAME=${COMPANY_NAME}\n")
